### ISSUE TITLE
Confusion about the version of numpy

### ISSUE THREAD

**Issue by M9JS** [CederGroupHub/chgnet#10]
I get the code running under the environment with numpy 1.21.6. It went wrong and said "File "pymatgen\util\coord_cython.pyx", line 1, in init pymatgen.util.coord_cython ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject". So I update the numpy to higher version like 1.22.0 or 1.23.0. It went wrong as well, said"C:\Users\86469\anaconda3\envs\chgnet\lib\site-packages\ase\md\nvtberendsen.py:95: RuntimeWarning: divide by zero encountered in scalar divide(self.temperature / old_temperature - 1.0) *".

**Comment by BowenD-UCB** [comment]
Hi, the runtime warning is a common warning message that is encountered in ASE MD call. This warning message will not trigger any bugs from my experience, you can check if the MD trajectory is generated successfully.

**Comment by M9JS** [comment]
Thanks for reply, I'll go check it :)
