### ISSUE TITLE
problem with ase.filters

### ISSUE THREAD

**Issue by Atefeh-Yadegarifard** [CederGroupHub/chgnet#107]
### Version

0.3.3

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### What happened?

Hello. 
I have installed the latest version of chgnet and I am unable to initialize it. 
chgnet version 0.3.3
ase version 3.22.1

### Code snippet

```python
from chgnet.model.model import CHGNet
```

### Log output

```shell
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 from chgnet.model.model import CHGNet

File ~/miniconda3/lib/python3.11/site-packages/chgnet/model/__init__.py:3
      1 from __future__ import annotations
----> 3 from chgnet.model.dynamics import CHGNetCalculator, MolecularDynamics, StructOptimizer
      4 from chgnet.model.model import CHGNet
      6 __all__ = ["CHGNet", "StructOptimizer", "MolecularDynamics", "CHGNetCalculator"]

File ~/miniconda3/lib/python3.11/site-packages/chgnet/model/dynamics.py:13
     11 from ase import Atoms, units
     12 from ase.calculators.calculator import Calculator, all_changes, all_properties
---> 13 from ase.filters import Filter, FrechetCellFilter
     14 from ase.md.npt import NPT
     15 from ase.md.nptberendsen import Inhomogeneous_NPTBerendsen, NPTBerendsen

ModuleNotFoundError: No module named 'ase.filters'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BowenD-UCB** [comment]
Hi,

The issue comes from the dependency in `ase.filters`
Please refer to ase install in the [release](https://github.com/CederGroupHub/chgnet/releases/tag/v0.3.3)
Before the official 

The update in the v0.3.3 is to implemente the new `FrechetCellFilter` in `StructOptimizer` for [better relaxation accuracy and speed.](https://github.com/CederGroupHub/chgnet/pull/101)
