### ISSUE TITLE
[Feature Request]: .xyz problem using ASE writer from .traj to .xyz (.traj generated by CHGNET)

### ISSUE THREAD

**Issue by caralvijo** [CederGroupHub/chgnet#117]
### Email (Optional)

vital@estidiantes.fisica.unam.mx

### Problem

I'm using MD2D to calculate diffusion so, I need an xyz file but when I use the ASE writer as follows there is a value error:

import ase
from ase.io import write
from ase.io.trajectory import Trajectory
traj = Trajectory('file.traj')
write('file.xyz', traj)

**ValueError: not enough values to unpack (expected 6, got 3)**

Do you have an idea to solve this?

### Proposed Solution

*

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BowenD-UCB** [comment]
If you index the trajectory object, can you get the corresponding `ase.Atoms` ?
If there's no issue with the trajectory object, this might be something related to [ASE](Omar Allam)

**Comment by caralvijo** [comment]
Yes, I can get the ase.Atoms, so I will check ASE documentation.
