### ISSUE TITLE
Issue with ASE

### ISSUE THREAD

**Issue by lkasillas** [CederGroupHub/chgnet#118]
### Version

main

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### What happened?

I am installing chgnet by doing pip install. I can not run any of the provided examples. I am getting an error due to ASE of which I have the latest stable version.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by janosh** [comment]
you should also get this warning https://github.com/CederGroupHub/chgnet/blob/44658ecc813732fbb5647d3391fcc5dbfddf8d43/chgnet/model/dynamics.py#L40-L46

is that not showing up?

**Comment by lkasillas** [comment]
Thanks, I got it to work but I never got that warning.

Luis
________________________________
