### ISSUE TITLE
out-of-memory issue

### ISSUE THREAD

**Issue by eric-yu-zhu** [CederGroupHub/chgnet#119]
My experience with chgnet is great. Thanks the team for developing and sharing it!
 
Recently, I got an out-of-memory issue while trying to relax a structure of 12,000 atoms. The experiment was done on an A6000 GPU having 48 GB memory. Below are a few questions:

Q1: What are the memory bottlenecks of chgnet?

Q2: Do you have a benchmark for memory usage of chgnet? My tests seem to show that 4000-atom-structure uses up 30 GB and 5000-atom-structure exceeds 48 GB. Make sense?

Q3: If the GPU memory issue cannot be resolved, should I try CPU version of chgnet? How many CPU cores are equivalent to the computing power of one decent GPU (e.g. V100) for running chgnet?

Any other suggestions?

**Comment by BowenD-UCB** [comment]
Q1,Q2 your test results are reasonable. I expect A100 to be able to simulate ~10K atoms. the exact number can vary from based on the structure you're simulating

Q3 I haven't done systematic tests on this, my experience is CPUs are significantly slower. For structure relxations CPUs might be OK, as they're not as costly as MDs.
