### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kaijiz** [CederGroupHub/chgnet#127]
### Email (Optional)

kaijiz@tamu.edu

### Version

v0.3.0

### Which OS(es) are you using?

- [X] MacOS
- [ ] Windows
- [ ] Linux

### What happened?

<img width="1379" alt="Screen Shot 2024-02-21 at 4 12 44 PM" src="https://github.com/CederGroupHub/chgnet/assets/126427660/6cffbd5f-b06d-4323-93a2-12e4b9cb534e">
Hi, when I tried to use the notebook example, I got this error and I don't know how to fix it, could you help me?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BowenD-UCB** [comment]
Thanks for the report.
We just added the install of ase gitlab to the example notebook.
The example notebook should work now, please check again.

**Comment by kaijiz** [comment]
hi, I still meet that problem, maybe it's because the version of ase is not right?

**Comment by BowenD-UCB** [comment]
If you're running this on Google colab, the ase gitlab version will be automatically installed by running the first block.
If you're running locally and don't have the latest ase version, please run 
`pip install git+https://gitlab.com/ase/ase`

**Comment by kaijiz** [comment]
Thanks for your reply. I know this and I have done this. But still met this error. I think ase 3.22 no longer has "filters" module. I am trying to find which version has this module.

**Comment by BowenD-UCB** [comment]
ASE pypi hasn't been released for 2 years.
So you have to install from their gitlab source with
`pip install git+https://gitlab.com/ase/ase`

**Comment by kaijiz** [comment]
So could you run this Notebook  "structure optimization" example without errors? I want to figure out it's my mistake or something wrong with the example.

**Comment by kaijiz** [comment]
oh i found how to fix it. you put "pip install git+https://gitlab.com/ase/ase" in the wrong place. should put in the "try" part instead of 'except' part.

**Comment by BowenD-UCB** [comment]
@kaijiz This is probably because you didn't restart the kernel in Google Colab.
Google Colab kermel should run the except part, because it needs to install chgnet

**Comment by thienbinh92** [comment]
I got the same issue. I install ase3.22.1. ase.filters module is not in the package anymore.
