### ISSUE TITLE
[Bug]: file not found

### ISSUE THREAD

**Issue by Anurag058-ai** [CederGroupHub/chgnet#173]
### Email (Optional)

anurag_k@mt.iitr.ac.in

### Version

v.0.3.8

### Which OS(es) are you using?

- [ ] MacOS
- [X] Windows
- [ ] Linux

### What happened?

Dear developers of CHGNet,

We are trying to develop the interface of LAMMPS for CHGNet by this link CHGNet: https://github.com/advancesoftcorp/lammps/tree/based-on-lammps_2Jun2022/src/ML-CHGNET 
But this link is not working and showing "page not found".

So, kindly resolve the issue.
It would be great that it will interest you.

Best Regards,
Anurag Kumar
Indian Institute of Technology, Roorkee
India

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BowenD-UCB** [comment]
Hi, the link should be updated now:
https://github.com/advancesoftcorp/lammps/tree/based-on-lammps_2Aug2023/src/ML-CHGNET
