### ISSUE TITLE
[Bug]: Error for Isolated atoms

### ISSUE THREAD

**Issue by chiang-yuan** [CederGroupHub/chgnet#176]
### Version

v0.3.5

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [ ] Linux

### What happened?

Was trying to calculate the diatomic dissociation energy curves and found chgnet could not take two isolated atoms beyond cutoff

### Code snippet

```python
from chgnet.model.dynamics import CHGNetCalculator

atoms = Atoms('HH', positions=[[0, 0, 0], [7, 0, 0]], cell=[14, 14.001, 14.002], pbc=True)
calc = CHGNetCalculator()

atoms.calc = calc

print(atoms.get_potential_energy())
```

### Log output

```shell
IndexError: too many indices for tensor of dimension 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BowenD-UCB** [comment]
solved in https://github.com/CederGroupHub/chgnet/commit/b819ef55f6dd87cc1e2b450c41cd47e5b06544e8
