### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by svnajman** [CederGroupHub/chgnet#193]
### Version

0.3.0

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### What happened?

I followed the procedure to initiate the fine-tuning, by creating a dummy fine-tuning dataset using CHGNet prediction with some random noise. 

### Code snippet

```python
for _ in range(100):
    structure = lmo.copy()
    # stretch the cell by a small amount
    structure.apply_strain(np.random.uniform(-0.1, 0.1, size=3))
    # perturb all atom positions by a small amount
    structure.perturb(0.1)

    pred = chgnet.predict_structure(structure)
```

### Log output

```shell
Traceback (most recent call last):
  File "/work/snajman/10.Nanographene/71.CHGNet_train/11.2D_perovskite/01_Training/vaspruns/trainf.py", line 25, in <module>
    pred = chgnet.predict_structure(structure)
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'chgnet' has no attribute 'predict_structure'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BowenD-UCB** [comment]
Can you please provide the full code? How was chgnet initiated?

**Comment by svnajman** [comment]
Thank you for the prompt reply. Here is the entire code:

import chgnet
import numpy as np
from pymatgen.core import Structure

try:
    from chgnet import ROOT

    lmo = Structure.from_file(f"{ROOT}/examples/mp-18767-LiMnO2.cif")
except Exception:
    from urllib.request import urlopen

    url = "https://raw.githubusercontent.com/CederGroupHub/chgnet/main/examples/mp-18767-LiMnO2.cif"
    cif = urlopen(url).read().decode("utf-8")
    lmo = Structure.from_str(cif, fmt="cif")

structures, energies_per_atom, forces, stresses, magmoms = [], [], [], [], []

for _ in range(100):
    structure = lmo.copy()
    # stretch the cell by a small amount
    structure.apply_strain(np.random.uniform(-0.1, 0.1, size=3))
    # perturb all atom positions by a small amount
    structure.perturb(0.1)

    pred = chgnet.predict_structure(structure)

    structures.append(structure)
    energies_per_atom.append(pred["e"] + np.random.uniform(-0.1, 0.1, size=1))
    forces.append(pred["f"] + np.random.uniform(-0.01, 0.01, size=pred["f"].shape))
    stresses.append(
        pred["s"] * -10 + np.random.uniform(-0.05, 0.05, size=pred["s"].shape)
    )
    magmoms.append(pred["m"] + np.random.uniform(-0.03, 0.03, size=pred["m"].shape))

from chgnet.data.dataset import StructureData, get_train_val_test_loader

dataset = StructureData(
    structures=structures,
    energies=energies_per_atom,
    forces=forces,
    stresses=stresses,  # can be None
    magmoms=magmoms,  # can be None
)
train_loader, val_loader, test_loader = get_train_val_test_loader(
    dataset, batch_size=8, train_ratio=0.9, val_ratio=0.05
)

from chgnet.model import CHGNet
from chgnet.trainer import Trainer

# Load pretrained CHGNet
chgnet = CHGNet.load()


# Optionally fix the weights of some layers
for layer in [
    chgnet.atom_embedding,
    chgnet.bond_embedding,
    chgnet.angle_embedding,
    chgnet.bond_basis_expansion,
    chgnet.angle_basis_expansion,
    chgnet.atom_conv_layers[:-1],
    chgnet.bond_conv_layers,
    chgnet.angle_layers,
]:
    for param in layer.parameters():
        param.requires_grad = False

# Define Trainer
trainer = Trainer(
    model=chgnet,
    targets="efsm",
    optimizer="Adam",
    scheduler="CosLR",
    criterion="MSE",
    epochs=5,
    learning_rate=1e-2,
    use_device="cpu",
    print_freq=6,
)

trainer.train(train_loader, val_loader, test_loader)

**Comment by BowenD-UCB** [comment]
You need to initialize chgnet first if you want to predict with it
`chgnet = CHGNet.load()`

The fine-tuning notebook has just been updated
