### ISSUE TITLE
[Bug] Energy divided twice by the number of atoms in MPTrjQuery.md

### ISSUE THREAD

**Issue by YutackPark** [CederGroupHub/chgnet#195]
### version
commit 2570b29 of main branch

### What happened?

I was working with [MPTrjQuery.md](https://github.com/CederGroupHub/chgnet/blob/main/examples/QueryMPtrj.md), modifying it on my purpose. I just found strange code in the `is_unique` function under the `UniquenessCheck` class.

Forgive me for not using a bug report template. Somehow GitHub doesn't let me raise an issue with it.

-------------------------------------

In the function `is_unique` under the `UniquenessCheck` class, the local variable `energy` is initialized as per atom energy.
https://github.com/CederGroupHub/chgnet/blob/180ffeafe43921827cc8fb11dbf57488d735bb35/examples/QueryMPtrj.md?plain=1#L170

In the same function, while the local variable `energy` is already a per-atom energy, it is divided by `n_atom` again to initialize `min_e_diff`.

https://github.com/CederGroupHub/chgnet/blob/180ffeafe43921827cc8fb11dbf57488d735bb35/examples/QueryMPtrj.md?plain=1#L213-L216

**Comment by BowenD-UCB** [comment]
Thanks for reporting!
I think you're right, this indeed appears to be a bug

**Comment by BowenD-UCB** [comment]
This has been fixed in ce1f29c925a4dfd1ca6e12f420b5854152406a11
