### ISSUE TITLE
Clarification on Pretrained CHGNet Models

### ISSUE THREAD

**Issue by kylincaster** [CederGroupHub/chgnet#209]
Dear all,

I am using the `matgl` package to run MD simulations with the **M3GNet** and **CHGNet** MLPs. I noticed that the `chgnet` project provides two versions (**0.2.0 and 0.3.0**). However, in the matgl project, there are two different pretrained models: **CHGNet-MPtrj-2023.12.1-PES-2.7M** and **CHGNet-MPtrj-2024.2.13-PES-11M**, as listed [here](https://github.com/materialsvirtuallab/matgl/tree/main/pretrained_models).

Could you please clarify the relationship between these pretrained models and advise which one is recommended for use?

Thank you for your help!

Best regards,
Kylin

**Comment by BowenD-UCB** [comment]
0.2.0 is deprecated, so don't use it unless you really need to.
MATGL implementation are newer and larger implementation of the legacy CHGNet in this repo.
CHGNet-MPtrj-2023.12.1-PES-2.7M and CHGNet-MPtrj-2024.2.13-PES-11M are essentially two different model sizes of 2.7M and 11M parameters, both trained on MPtrj dataset.

Depending on your GPU memory you should choose the reasonable size for yourself. 
In general, the 2.7M one or the 0.3.0 legacy implementation should be good
