### ISSUE TITLE
Unused `get_loader()`

### ISSUE THREAD

**Issue by janosh** [CederGroupHub/chgnet#30]
Can we delete `get_loader()`? Looks like it's an unused utility function.

https://github.com/CederGroupHub/chgnet/blob/b59d371b4dd32b872e5a7e303aacfe3b8f31b94d/chgnet/data/dataset.py#L720-L744

**Comment by BowenD-UCB** [comment]
It's occationally used to separately load val dataset and test dataset. Let's keep it
