### ISSUE TITLE
Fine tuning CHGNet with DFT energies and forces 

### ISSUE THREAD

**Issue by Atefeh-Yadegarifard** [CederGroupHub/chgnet#61]
Dear CHGNet developers,
Hello. 
I would like to request an example for how CHGNet can be trained with additional DFT data (calculated by the users). Specifically the format of the data that has to be used for training. 
Thank you.

**Comment by BowenD-UCB** [comment]
For fine-tuning code, please refer to:
https://github.com/CederGroupHub/chgnet/blob/main/examples/fine_tuning.ipynb

For parsing VASP output into fine-tuning dataset, please refer to:
https://github.com/CederGroupHub/chgnet/blob/main/chgnet/utils/vasp_utils.py
