### ISSUE TITLE
units and format when compared with trajectories (ASE)

### ISSUE THREAD

**Issue by bkmi** [CederGroupHub/chgnet#75]
Just going on the `README.md`, the units and shapes of results from `prediction = chgnet.predict_structure(structure)` and `relaxer = StructOptimizer(); result = relaxer.relax(structure)` are different. Energies is easily fixed by multiplying by number of atoms, but the other quantities don't seem to have such a simple relationship.

I figure that you have clear units from `predict_structure`, but when I look at ASE documentation, the units from their atoms object is not 100% clear to me. Furthermore, the "stresses" prediction `prediction["s"]` is a completely different shape from the `results["trajectory"][-1]`. How do I convert between them?

**Comment by BowenD-UCB** [comment]
ASE uses stress, please read:
https://gitlab.com/ase/ase/-/blame/master/ase/atoms.py#L826
