### ISSUE TITLE
Periodic boundary conditions?

### ISSUE THREAD

**Issue by shivang-22** [CederGroupHub/chgnet#82]
Hello, CHGNet seems like one of the most extensive MLIP's, but from what I understand it is only applicable to isolated molecules? Is that correct, or can we also simulate bulk materials (like FCC aluminium)? If so, how would one take care of boundary conditions? Thanks in advance!

**Comment by BowenD-UCB** [comment]
CHGNet is mostly trained on periodic crystalline materials from [Materials Project](https://next-gen.materialsproject.org/)

We're interfaced through pymatgen, where periodic boundary condition are automatically enforced in the [Structures](https://pymatgen.org/pymatgen.core.html#module-pymatgen.core.structure)
