### ISSUE TITLE
`IndexError` on `predict_structure`

### ISSUE THREAD

**Issue by Yong-Q** [CederGroupHub/chgnet#85]
## Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [x] Linux

## What happened?

The following code snippet fails:

```py
from chgnet.model.model import CHGNet
from pymatgen.core import Structure

chgnet = CHGNet.load()
structure = Structure.from_file('example/mp-2878.cif')
prediction = chgnet.predict_structure(structure)

for key, unit in [
    ("energy", "eV/atom"),
    ("forces", "eV/A"),
    ("stress", "GPa"),
    ("magmom", "mu_B"),
]:
    print(f"CHGNet-predicted {key} ({unit}):\n{prediction[key[0]]}\n")
```

### Error Message

```py
CHGNet initialized with 400,438 parameters
Traceback (most recent call last):
  File "<script>", line 6, in <module>
    prediction = chgnet.predict_structure(structure)
  File "/path/to/chgnet/model/model.py", line 551, in predict_structure
    return self.predict_graph(...)
  File "/path/to/chgnet/model/model.py", line 340, in forward
    batched_graph = BatchedGraph.from_graphs(...)
  File "/path/to/chgnet/model/model.py", line 754, in from_graphs
    center=atom_cart_coords[graph.atom_graph[:, 0]],
IndexError: tensors used as indices must be long, byte or bool tensors
```

**Comment by BowenD-UCB** [comment]
I can't reproduce this error

**Comment by janosh** [comment]
Me neither.

**Comment by Yong-Q** [comment]
Why is this, I installed it via pip, this problem occurs in both cpu and gpu
[1.txt](https://github.com/CederGroupHub/chgnet/files/13065805/1.txt)

**Comment by Yong-Q** [comment]
#structure = Structure.from_file(f"{ROOT}/examples/mp-18767-LiMnO2.cif")

    structure = Structure.from_file("./mp-18767-LiMnO2.cif")  
I only changed this one item, but looking at the output shouldn't be the problem

**Comment by Yong-Q** [comment]
> Me neither.
#structure = Structure.from_file(f"{ROOT}/examples/mp-18767-LiMnO2.cif")

structure = Structure.from_file("./mp-18767-LiMnO2.cif")  
I only changed this one item, but looking at the output shouldn't be the problem

**Comment by BowenD-UCB** [comment]
I suppose it's a version issue of pymatgen and CHGNet. Can you try upgrade pymatgen and CHGNet? @Yong-Q

**Comment by Yong-Q** [comment]
ok，i will try



---Original---
From: "Bowen ***@***.***&gt;
Date: Mon, Oct 23, 2023 11:42 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [CederGroupHub/chgnet] `IndexError` on `predict_structure` (Issue#85)




 
I suppose it's a version issue of pymatgen and CHGNet. Can you try upgrade pymatgen and CHGNet? @Yong-Q

**Comment by Yong-Q** [comment]
good

**Comment by Yong-Q** [comment]
> 我想这是pymatgen和CHGNet的版本问题。你能尝试升级pymatgen和CHGNet吗？

I would like to ask how the prediction of energy etc. can be improved by constructing the Angle relationship on the GNN structure
