### ISSUE TITLE
[Bug]: Energy error

### ISSUE THREAD

**Issue by Yong-Q** [CederGroupHub/chgnet#92]
### Email (Optional)

3244608729@qq.com

### Version

0.3.0

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### What happened?

The result of the test was" CHGNet predicted energy (eV/atom):-4.5642852783203125"
but ture is "-1.119ev/atom"

### Code snippet

```python
prediction = chgnet.predict_structure(structure)

for key, unit in [
    ("energy", "eV/atom"),
    ("forces", "eV/A"),
    ("stress", "GPa"),
    ("magmom", "mu_B"),
]:
    print(f"CHGNet-predicted {key} ({unit}):\n{prediction[key[0]]}\n")
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Yong-Q** [comment]
The predicted structure is mp-696138

**Comment by BowenD-UCB** [comment]
If you're get the -1.119 eV/atom from [Materials Project ](https://next-gen.materialsproject.org/materials/mp-696138/#thermodynamic_stability)
This value from MP is formation energy, not the energy that CHGNet is predicting.

Please read carefully the terminologies from MP and CHGNet paper before reporting the bug in the github.
if you're not sure, please raise these questions to [Discussion](https://github.com/CederGroupHub/chgnet/discussions).
