### ISSUE TITLE
[Bug]: Error Encountered when Using 'predict_structure' for Structure Prediction

### ISSUE THREAD

**Issue by hoon-ock** [CederGroupHub/chgnet#99]
### Version

tried both v0.2.0 and v0.3.0 versions

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### What happened?

I encountered the following error when using the 'predict_structure' function to feed the structure, like this: 'prediction = chgnet.predict_structure(structure, return_crystal_feas=True)

![image](https://github.com/CederGroupHub/chgnet/assets/93333323/502d837e-038c-4b10-88ed-a7d07d7407a4)

structure: 
![image](https://github.com/CederGroupHub/chgnet/assets/93333323/38e24951-1d28-4e91-87fb-4407b30240d9)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ZLG001** [comment]
got similar error, with updated verison of pymatgen (2023.11.12) and chgnet (0.3.2). Thanks to the developer.

**Comment by BowenD-UCB** [comment]
@hoon-ock 
Can you provide your pymatgen version that generates the issue?
can you please try update you pymatgen version and see if that helps?

**Comment by cy0752** [comment]
I encountered the same error. I'm using pymatgen(2024, 4) and the newest chgnet, and torch (1.11)
